packages:
  - 'apps/*'
  - 'services/*'
  - 'packages/*'
allowBuilds:
  '@clerk/shared': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  less: true
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: true
