[project]
name = "ai-engine"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.92.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.135.3",
    "langchain>=1.2.15",
    "pgvector>=0.4.2",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.44.0",
    "voyageai>=0.3.7",
]

[dependency-groups]
dev = []
